"""config package — project-wide settings."""
from .settings import (
    ROOT, PATHS, ROUTES, RBA_CASH_RATE, CPI_ANNUAL, FUEL_INDEX,
    COVID, DATA_START, DATA_END, FREQ, SEASON_M,
    GB_PARAMS, CV_FOLDS, CV_TEST_SIZE, TEST_WEEKS, N_BOOTSTRAP,
    LP_DEFAULTS, DID_CONFIG, FEATURE_COLS, FEATURE_NAMES,
)
